### ISSUE TITLE
Experimental transform.

### ISSUE THREAD

**Issue by ronanyeah** [coStars/integrative-frontend-example#1]
Is there a reason you need an [experimental](https://babeljs.io/docs/plugins/#presets-stage-x-experimental-presets-) [stage-0](https://github.com/coStars/integrative-frontend-example/blob/master/.babelrc#L3) babel transform?

**Comment by ibraghada** [comment]
Actually, we have watched a tutorial on react and we just followed it step by step where they used stage-0 ! 

That's it :D
